#!/usr/bin/env bash
set -euo pipefail

repo_dir=$(cd "$(dirname "$0")/.." && pwd)
worker_config=${1:?Usage: configure-config-service-secrets.sh <wrangler-config> <phone-export>}
phone_export=${2:?Usage: configure-config-service-secrets.sh <wrangler-config> <phone-export>}
edge_secret_file="$repo_dir/private/edgetunnel.env"
profile_secret_file="$repo_dir/private/secrets.env"
service_secret_file="$repo_dir/private/config-service.env"
wrangler_version=4.127.1

if [[ ! -f "$phone_export" || ! -f "$edge_secret_file" ]]; then
  echo "Missing phone export or private/edgetunnel.env" >&2
  exit 1
fi

extract_field() {
  local node_name=$1
  local field_name=$2
  perl -ne '
    BEGIN { ($node, $field) = @ARGV[0,1]; @ARGV = @ARGV[2..$#ARGV] }
    if (/^\Q$node\E\s*=.*?\b\Q$field\E=([^,\r\n]+)/) {
      print $1;
      exit;
    }
  ' "$node_name" "$field_name" "$phone_export"
}

https_username=$(extract_field jp username)
https_password=$(extract_field jp password)
tuic_username=$(extract_field uh username)
tuic_password=$(extract_field uh password)
tuic_uuid=$(extract_field uh uuid)
hy2_username=$(extract_field ux username)
hy2_password=$(extract_field ux password)

set -a
# This file is generated by our own script and contains only KEY=value lines.
# shellcheck disable=SC1090
source "$edge_secret_file"
set +a

if [[ -f "$service_secret_file" ]]; then
  # shellcheck disable=SC1090
  source "$service_secret_file"
fi
access_token=${CONFIG_ACCESS_TOKEN:-$(openssl rand -hex 24)}
managed_url="https://config.fallback.page/$access_token/surge.conf"

declare -a names=(
  ACCESS_TOKEN HTTPS_USERNAME HTTPS_PASSWORD TUIC_USERNAME TUIC_PASSWORD
  TUIC_UUID HY2_USERNAME HY2_PASSWORD EDGETUNNEL_UUID
)
declare -a values=(
  "$access_token" "$https_username" "$https_password" "$tuic_username"
  "$tuic_password" "$tuic_uuid" "$hy2_username" "$hy2_password"
  "$EDGETUNNEL_UUID"
)

umask 077
{
  printf 'SURGE_MANAGED_URL=%s\n' "$managed_url"
  printf 'HTTPS_USERNAME=%s\n' "$https_username"
  printf 'HTTPS_PASSWORD=%s\n' "$https_password"
  printf 'TUIC_USERNAME=%s\n' "$tuic_username"
  printf 'TUIC_PASSWORD=%s\n' "$tuic_password"
  printf 'TUIC_UUID=%s\n' "$tuic_uuid"
  printf 'HY2_USERNAME=%s\n' "$hy2_username"
  printf 'HY2_PASSWORD=%s\n' "$hy2_password"
  printf 'EDGETUNNEL_UUID=%s\n' "$EDGETUNNEL_UUID"
} > "$profile_secret_file"

printf 'CONFIG_ACCESS_TOKEN=%s\n' "$access_token" > "$service_secret_file"
chmod 600 "$profile_secret_file" "$service_secret_file"

for index in "${!names[@]}"; do
  if [[ -z "${values[$index]}" ]]; then
    echo "Could not resolve secret: ${names[$index]}" >&2
    exit 1
  fi

  uploaded=false
  for attempt in 1 2 3; do
    if printf '%s' "${values[$index]}" |
      npx --yes "wrangler@$wrangler_version" secret put "${names[$index]}" --config "$worker_config"; then
      uploaded=true
      break
    fi
    echo "Retrying ${names[$index]} ($attempt/3)..." >&2
  done

  if [[ "$uploaded" != true ]]; then
    echo "Failed to upload secret: ${names[$index]}" >&2
    exit 1
  fi
done

echo "Uploaded config-service secrets and refreshed ignored local secret files."
